### PR TITLE
Fix building for musl libc

### LINKED ISSUE #154: Unable to install pyo3-pack on Alpine Linux
This is due to the lack of support for PEP 517 (See #2).

We should release a source distribution of pyo3-pack.

### PR DESCRIPTION
**Pull request by messense**
Closes #154

### CODE REVIEW

**Comment by messense** [comment]
cc @thedrow

**Comment by konstin** [comment]
Thank you!

**Comment by messense** [comment]
Seems that `-C target-feature=-crt-static` breaks https://github.com/PyO3/maturin/runs/1918499503

**Comment by konstin** [comment]
Yeah, I've overlooked that it needs to be guarded on libraries only. Should be fixed in 53dd4c2a2b548e8e9a1a390dccf161f61ee6137e

**Pull request merged**
