### PR TITLE
Add workspace lock file to sdist as a fallback

### PR DESCRIPTION
**Pull request by messense**
See https://github.com/sourmash-bio/sourmash/pull/2393#issue-1474253735

> Figure out how to pull `Cargo.lock` from workspace root.

cc @luizirber

### CODE REVIEW

**Comment by messense** [comment]
bors retry

**Comment by luizirber** [comment]
:tada: thanks for the PR =]

I tried it out in https://github.com/sourmash-bio/sourmash/pull/2393 but it still doesn't quite work because I'm messing with `manifest-path` to pick up the crate Cargo.toml, while wanting to use the workspace Cargo.lock. Something like this structure:

```
.
├── Cargo.lock
├── Cargo.toml
├── pyproject.toml
└── src
    ├── python_package
    └── rust_crate
        └── Cargo.toml
```
- If I try to use the workspace Cargo.toml (don't set `manifest-path` in `pyproject.toml`) , it doesn't find a valid package section.
- If I set `manifest-path` to `src/rust_crate/Cargo.toml`, it works as long as I don't use `--locked`
- If I use `--locked`, it fails because it doesn't recognize that it is a workspace (because the `manifest-path` is set to `src/rust_crate/Cargo.toml`, not the workspace one)

I started looking into the codebase earlier this week and [writing a test case](https://github.com/PyO3/maturin/compare/main...luizirber:maturin:lirber/workspace_lock) similar to the structure I just posted, but hit issues around the [CargoToml](https://github.com/PyO3/maturin/blob/d66555807f38350f63efb8da09aa7efcd0b96fd1/src/cargo_toml.rs#L27) parsing because it expects a non-workspace Cargo.toml, but going all the way to use the "official" cargo metadata was going to change a lot of code.

**Comment by messense** [comment]
I've release 0.14.7b1 to pypi, you can give it try:

```toml
[build-system]
requires = ["maturin==0.14.7b1", "cffi"]
build-backend = 'maturin'
```

https://pypi.org/project/maturin/0.14.7b1/

**Comment by messense** [comment]
@luizirber `0.14.7` is out: https://github.com/PyO3/maturin/releases/tag/v0.14.7

**Comment by luizirber** [comment]
> I bumped `maturin` in [nixpkgs](https://github.com/NixOS/nixpkgs/pull/205211/) recently, once `0.14.7` is release I'll bump it again (it does trigger a lot of CI jobs, so I'll skip `0.14.6`)

PR: https://github.com/NixOS/nixpkgs/pull/207064

**Pull request merged**
