### PR TITLE
Guessed platform may be incorrect, so do not force compilation with it

### PR DESCRIPTION
**Pull request by al626**
See https://github.com/PyO3/maturin/issues/478

This reverts most of https://github.com/PyO3/maturin/pull/429 while hopefully keeping the issue described in the PR fixed.

Pretty new to rust so feel free to close & fix otherwise if this isn't suitable.

### CODE REVIEW

**Comment by messense** [comment]
Thanks, I think we should remove the usage of `Platform::guess_current()`.

**Review by messense — APPROVED** [review]

**Comment by messense** [comment]
Rethinking about this, we should probably avoid using `Platform::guess_current()` to set [`Target::env`](https://github.com/PyO3/maturin/blob/1239c4f7ffdd6c1d769405c6d51e95a173ae72a7/src/target.rs#L113) since the maturin linux wheel is built with musl libc, the `target_env` of `platforms` would always be `musl`?

**Comment by al626** [comment]
This is slightly confusing; there are two separate concepts:

1. Building maturin
2. Using maturin to build something else.

My understanding of the situation is for (1), it's important to have `Platform::guess_current()` as otherwise tools like `cargo build` and `cargo test` would not work; a target would need to be explicitly specified (e.g. `cargo build --target x86_64-unknown-linux-gnu` ). Here, `Platform::guess_current()` works as `Platform` is compiled from source in the maturin build.

For (2), a precompiled version of maturin is used, so `Platform::guess_current()` will not return the correct `env`, but does return the correct `arch` and `os` (as pip wheels are compiled for a particular `os` and `arch` but not `env`). `os` info is necessary (e.g. to differentiate between windows and linux).

My opinion is that if we were doing things properly, we should strip out uses of `Target` (which wraps `Platform::guess_current()`) for everything involved in using maturin to build other things (e.g. `develop.rs`), and replace with something a bit more specific that only stores and uses `os` info (e.g. `std::env::consts::OS`). However, this is a fairly large change and may be overkill.

We should also write a test that ensures that a maturin compiled for `musl` can build something for `gnu` without the `musl` toolchain installed.

What do you think about the above? I can do this, but will be slow (time limitations + new to rust).

Thanks.

**Comment by messense** [comment]
Merged in #487, thanks!

**Pull request closed without merging**
