### PR TITLE
CI: use latest Python 3.10 instead of 3.10.0

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by messense** [comment]
> "/LIBPATH:C:\\hostedtoolcache\\windows\\Python\\3.10.0\\x64\\libs"

Odd, it installed 3.10.8 but the `LIBPATH` refers to 3.10.0.

**Comment by messense** [comment]
```
 --- stdout
  cargo:rerun-if-env-changed=PYO3_CROSS
  cargo:rerun-if-env-changed=PYO3_CROSS_LIB_DIR
  cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_VERSION
  cargo:rerun-if-env-changed=PYO3_CROSS_PYTHON_IMPLEMENTATION
  cargo:rerun-if-env-changed=PYO3_PRINT_CONFIG

  -- PYO3_PRINT_CONFIG=1 is set, printing configuration and halting compile --
  implementation=CPython
  version=3.10
  shared=true
  abi3=false
  lib_name=python310
  lib_dir=C:\hostedtoolcache\windows\Python\3.10.0\x64\libs
  executable=D:\a\maturin\maturin\test-crates\venvs\develop-pyo3-mixed-py-subdir-cpython\Scripts\python.exe
  pointer_width=64
  build_flags=
  suppress_build_script_link_lines=false
```

```bash
$ test-crates\venvs\develop-pyo3-mixed-py-subdir-cpython\Scripts\python.exe --version
3.10.8
```

I don't understand...

**Comment by messense** [comment]
Update to pyo3 main branch seems to have fixed the issue, is there any change related I didn't know?

**Comment by davidhewitt** [comment]
Looks probably related to #1214?

**Comment by davidhewitt** [comment]
> Update to pyo3 main branch seems to have fixed the issue, is there any change related I didn't know?

I... don't think so. Do you think there's a way to repro locally? I can try to help debug this.

**Comment by messense** [comment]
Yes, I want to isolate the problem first, the current CI setup doesn't really test all supported Python versions, I hope to expand it in #1214

> I... don't think so. Do you think there's a way to repro locally? I can try to help debug this.

No, it's Windows x64 I don't have a working environment. I suspect it might related to build cache, https://github.com/PyO3/maturin/pull/1228/commits/6cdee75add5d95625fabb82c67b1023f056b8ce6 also  passes `cargo nextest run`.

**Comment by davidhewitt** [comment]
I have a Windows x64 machine that I can run some stuff on later in the week if you have a recommendation of what I'll need to run? 😄

**Comment by messense** [comment]
> if you have a recommendation of what I'll need to run?

Unfortunately I don't have a recommendation at the moment. Without ssh like remote login support, debugging Windows build on GitHub Actions is quite painful 😓.

**Comment by davidhewitt** [comment]
Hmm ok. If I get some time mid-week I can try to run this on my windows machine, no guarantee!

**Comment by messense** [comment]
I think it's related to https://github.com/PyO3/maturin/issues/1219#issuecomment-1292903379 as well

```
runneradmin@fv-az319-905 MINGW64 /d/a/maturin/maturin/test-crates/targets/develop-pyo3-mixed-py-subdir/debug/build
# cat pyo3-build-config-c0fb8d48463d7859/out/pyo3-build-config.txt
implementation=CPython
version=3.10
shared=true
abi3=false
lib_name=python310
lib_dir=C:\hostedtoolcache\windows\Python\3.10.0\x64\libs
executable=D:\a\maturin\maturin\test-crates\venvs\develop-pyo3-mixed-py-subdir-cpython\Scripts\python.exe
pointer_width=64
build_flags=
suppress_build_script_link_lines=false
```

The `3.10.0` is definitely coming from this cached `pyo3-build-config.txt` file thus removing build cache makes it work.

**Comment by messense** [comment]
@davidhewitt I think the repro steps are:

* Create an venv with older Python version say 3.10.0 (or 3.9.x) then run `maturin develop` with a non-abi3 extension module
* Recreate the venv at the same path with a newer Python version say 3.10.8, run `maturin develop` again to trigger the build error

**Comment by messense** [comment]
For now we can workaround the issue by deleting the problematic caches.

**Comment by messense** [comment]
> @davidhewitt I think the repro steps are:
> 
> * Create an venv with older Python version say 3.10.0 (or 3.9.x) then run `maturin develop` with a non-abi3 extension module
> * Recreate the venv at the same path with a newer Python version say 3.10.8, run `maturin develop` again to trigger the build error

I have a repro for Linux in https://github.com/PyO3/pyo3/issues/2724

**Pull request merged**
