### PR TITLE
Document binary and library in a single package by entrypoint workaround

### PR DESCRIPTION
**Pull request by konstin**
Inspired by https://github.com/PyO3/maturin/issues/368#issuecomment-1503752982

Preview: https://deploy-preview-1565--maturin-guide.netlify.app/bindings.html#both-binary-and-library

CC @nanthony007

### CODE REVIEW

**Comment by nanthony007** [comment]
This is awesome!

**Comment by messense** [comment]
File path on Windows is ridiculously [complicated](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats), maybe we should simplify the test case to not assert file paths.

**Comment by konstin** [comment]
The tests are passing now, i've removed checks for platforms with inconsistent behaviors. I think the current `check_installed.py` is also good as documentation.

**Review by messense — APPROVED** [review]
bors r+

**Comment by konstin** [comment]
bors retry

looks like a network error: https://github.com/PyO3/maturin/actions/runs/4760507648/jobs/8460910927

**Comment by konstin** [comment]
bors r+

discovering more strange platform behavior as i go

**Comment by konstin** [comment]
bors retry

**Pull request merged**
