### PR TITLE
Build i686 musl wheel on GitHub Action

### PR DESCRIPTION
**Pull request by messense**
A lot of time spent on installing maturin to build wheel for 32-bit linux: https://github.com/messense/rjieba-py/runs/1933811414?check_suite_focus=true

### CODE REVIEW

**Comment by konstin** [comment]
Afaik we can build this as a regular target on ubuntu-latest, so no need to go through cross, which I'd prefer

**Comment by messense** [comment]
I was originally try to use a regular target, but it now has too many `if`s makes things complicated.

**Comment by konstin** [comment]
Do you think https://github.com/PyO3/maturin/compare/github-actions-i686-unknown-linux-musl would work?

**Comment by messense** [comment]
I think that should work, thanks!

**Comment by messense** [comment]
Closing in favor of https://github.com/PyO3/maturin/commit/64cf56dd1600142d71729df22b075a8ba97bc7ba

**Comment by konstin** [comment]
My version seems to fail: https://github.com/PyO3/maturin/runs/1963814800?check_suite_focus=true

Do you by chance know why?

**Comment by messense** [comment]
Hmm, I am not sure. Looked at [ring's build script](https://github.com/briansmith/ring/blob/930b97b0c95acebf1ae61698c0ed3c171cac00ea/mk/install-build-tools.sh#L65), it uses clang instead of gcc for musl targets.

**Pull request closed without merging**
