### PR TITLE
Add prerelase support to release workflow

### PR DESCRIPTION
**Pull request by messense**

### CODE REVIEW

**Comment by konstin** [comment]
That's neat, I wasn't aware it would be that easy

**Comment by messense** [comment]
https://github.com/PyO3/maturin/runs/2523443534?check_suite_focus=true

```
Run svenstaro/upload-release-action@v2
  with:
    repo_token: ***
    file: *.{tar.gz,zip,deb}
    file_glob: true
    tag: refs/tags/v0.10.5-beta.2
    prerelease: true
```

It's correctly passed `prerelease: true` to `svenstaro/upload-release-action@v2` but it doesn't seem to work correctly for https://github.com/PyO3/maturin/releases/tag/v0.10.5-beta.2

**Comment by messense** [comment]
Should be fixed by https://github.com/PyO3/maturin/commit/ef6e70b13da3ffc31bf24138c72acbefe45c2e1d

**Comment by messense** [comment]
It works now: https://github.com/PyO3/maturin/releases/tag/v0.10.5-beta.3

**Pull request merged**
