### PR TITLE
Query macOS deployment target version from rustc

### PR DESCRIPTION
**Pull request by messense**
Part of #1268

### CODE REVIEW

**Comment by davidhewitt** [comment]
@messense this looks interesting, do you think we should add the same to setuptools-rust?

**Comment by messense** [comment]
setuptools already have it's only way to deal with macOS deployment target version from `wheel`: https://github.com/pypa/wheel/blob/814c2efe8e40051039c5a6de6945e04ecdd162ee/src/wheel/macosx_libfile.py#L392

I also want to implement some similar in maturin (#1252) once https://github.com/m4b/goblin/pull/341 is released.

**Comment by davidhewitt** [comment]
Ah ok 👍

**Pull request merged**
