### PR TITLE
Enable `extension-module` feature in `pyproject.toml` in project templates

### PR DESCRIPTION
**Pull request by messense**
Implements https://github.com/PyO3/maturin/issues/325#issuecomment-1416697270.

Thanks for the idea @jmhodges!

### CODE REVIEW

**Comment by messense** [comment]
This has the benefits of that `cargo test` will work out of the box for non-Python related tests written in Rust. I guess we can also add `maturin test` command that invokes `cargo test` with `auto-initialize` feature enabled to support testing Python related tests written in Rust?

What do you guys think? @konstin @davidhewitt

**Review by konstin — APPROVED** [review]
good idea!

**Comment by messense** [comment]
bors r=konstin

**Comment by messense** [comment]
bors retry

**Comment by davidhewitt** [comment]
> This has the benefits of that `cargo test` will work out of the box for non-Python related tests written in Rust. I guess we can also add `maturin test` command that invokes `cargo test` with `auto-initialize` feature enabled to support testing Python related tests written in Rust?

I think it's less necessary, because it's easy to add a `pyo3` dev-dependency with the `auto-initialize` feature. Plus, not all projects use `auto-initialize`, some use custom interpreter setup at the beginning of each test.

**Pull request merged**
