### PR TITLE
Support Aarch64 on OpenBSD

### PR DESCRIPTION
**Pull request by dkarama**
Took almost a day to build maturin with this diff:-

```
$OpenBSD$

Index: src/target.rs
--- src/target.rs.orig
+++ src/target.rs
@@ -74,7 +74,7 @@ fn get_supported_architectures(os: &Os) -> Vec<Arch> {
         Os::Windows => vec![Arch::X86, Arch::X86_64, Arch::Aarch64],
         Os::Macos => vec![Arch::Aarch64, Arch::X86_64],
         Os::FreeBsd => vec![Arch::X86_64],
-        Os::OpenBsd => vec![Arch::X86_64],
+        Os::OpenBsd => vec![Arch::X86_64, Arch::Aarch64],
     }
 }
 
@@ -157,6 +157,14 @@ impl Target {
                 };
                 let release = info.release().replace(".", "_").replace("-", "_");
                 format!("openbsd_{}_amd64", release)
+            }
+            (Os::OpenBsd, Arch::Aarch64) => {
+                let info = match PlatformInfo::new() {
+                    Ok(info) => info,
+                    Err(error) => panic!("{}", error),
+                };
+                let release = info.release().replace(".", "_").replace("-", "_");
+                format!("openbsd_{}_arm64", release)
             }
             (Os::Linux, _) => {
                 let mut tags = vec![format!("{}_{}", manylinux, self.arch)];
```

Obviously some refractoring was done since so I'm posting with some adaptation. The configuration is same as in https://github.com/PyO3/maturin/pull/568. Build and run tested with py-adblock (All tests pass). Most probably there won't be anymore archs to add since sparc64 is failing at compiling rust and I guess it is unsupported in maturin or is it?

```
    Finished release [optimized] target(s) in 208m 30sock                                                                
📦 Built wheel for abi3 Python ≥ 3.6 to /usr/ports/pobj/py-adblock-0.4.4-python3/python-adblock-0.4.4/target/wheels/adblock-0.4.4-cp36-abi3-openbsd_6_9_arm64.whl
```

### CODE REVIEW

**Comment by dkarama** [comment]
The error seems unrelated.

**Comment by konstin** [comment]
Looks good, could you also please add the output of `python -m sysconfig` [here](https://github.com/PyO3/maturin/tree/main/sysconfig)?

**Comment by dkarama** [comment]
> Looks good, could you also please add the output of `python -m sysconfig` [here](https://github.com/PyO3/maturin/tree/main/sysconfig)?

Sure.

**Comment by konstin** [comment]
Thank you!

**Pull request merged**
