### PR TITLE
Fix aarch64 EXT_SUFFIX

### PR DESCRIPTION
**Pull request by ijl**

### CODE REVIEW

**Comment by ijl** [comment]
It takes about six minutes to compile maturin on a drone.io aarch64 worker. It would be helpful if you could distribute on PyPI for aarch64. Something like this is a start:

```yaml
kind: pipeline
name: linux_aarch64
platform:
  arch: arm64
steps:
- name: test
  image: python:3.8-buster
  environment:
    PATH: "/root/.local/bin:/root/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  commands:
    - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly --profile minimal -y
    - python3.8 -m pip wheel --no-binary=maturin .
```

**Comment by konstin** [comment]
Thank you!

I've activate drone.io and made an initial PR with your configuration. I'll see if I can make aarch64 releases from that.

**Comment by konstin** [comment]
There's now a (alpha) release with an aarch64 wheel on pypi: https://pypi.org/project/maturin/0.8.0-alpha.2/#files

When tagging the next release, an aarch64 wheel will be included.

**Comment by ijl** [comment]
@konstin thank you, maturin-0.8.0_alpha.2-py3-none-manylinux2014_aarch64.whl works well.

**Pull request merged**
