### PR TITLE
Fix sdist with local path dependencies on Windows

### LINKED ISSUE #579: Maturin sdists fails on Windows when using local dependencies
Please provide the following information: 
 * Your python version (`python -V`): 3.x
 * Your pip version (`pip -V`): 
   * If this isn't the [latest pip version](https://pip.pypa.io/en/stable/news/), have you checked using the latest pip version?
 * The version of the bindings you're using, if any (e.g. `pyo3`, `rust-cpython` or `cffi`): 0.13.2
 * Does `cargo build` work? Yes
 * If on windows, have you checked that you aren't accidentally using unix path (those with the forward slash `/`)? Yes

Hi,

I've been trying to provide a source distribution for pywinpty (https://github.com/spyder-ide/pywinpty), which only works for Windows. This package depends on pywinpty_findlib, which is a local dependency that is specified in the Cargo.toml as follows:

```toml
[build-dependencies]
cxx-build = {version = "1.0.45", features = ["parallel"]}
pywinpty_findlib = { version = "=0.3.0", path = "findlib" }
which = "4.1.0"
```

When I try to invoke `maturin sdist`, it fails with the following message:

```
💥 maturin failed
  Caused by: Failed to build source distribution
  Caused by: Failed to add local dependency pywinpty_findlib at /C:/Users/quansight/pywinpty/findlib to the source distribution
  Caused by: Failed to query file list from cargo: exit code: 101
--- Stdout:

--- Stderr:
error: manifest path `/C:/Users/quansight/pywinpty/findlib\Cargo.toml` does not exist
``` 

My guess is that for some reason, forward and backward slashes are getting mixed up, which is preventing the correct localization of the local dependency `Cargo.toml`. This also occurs when calling `maturin build`, but not when calling `maturin develop`

### PR DESCRIPTION
**Pull request by messense**
Closes #579

### CODE REVIEW

**Comment by andfoy** [comment]
@messense, does this also fix the issues related to `maturin build`?

**Comment by messense** [comment]
> does this also fix the issues related to `maturin build`?

Yes, the sdist generation code is shared.

**Comment by messense** [comment]
I'm gonna merge this and publish a new beta release so users can try it.
@konstin Feel free to ask for changes, I can do follow-up PR to fix them.

**Comment by konstin** [comment]
Thanks, looks good! BTW @messense feel free to publish 0.11.0 final.

**Pull request merged**
